### ISSUE TITLE
Integration tests for Katib experiments

### ISSUE THREAD

**Issue by i-chvets** [canonical/katib-operators#103]
# Description
Integration tests for Katib experiments need to be created to ensure all Katib images are functioning as expected.
Integration tests should be a part of bundle test which already has a test for creating a single experiment.
These integration tests should cover the following Katib container images:
- katib/cmd/earlystopping/medianstop/v1beta1
- katib/cmd/metricscollector/v1beta1/tfevent-metricscollector
- katib/cmd/metricscollector/v1beta1/file-metricscollector
- katib/cmd/suggestion/hyperopt/v1beta1
- katib/cmd/suggestion/hyperband/v1beta1
- katib/cmd/suggestion/pbt/v1beta1
- katib/cmd/suggestion/goptuna/v1beta1
- katib/cmd/suggestion/skopt/v1beta1
- katib/cmd/suggestion/optuna/v1beta1
- katib/cmd/suggestion/nas/darts/v1beta1
- katib/cmd/suggestion/nas/enas/v1beta1

# Design

TO-DO: Add any related design points here.

# Testing

**Comment by kimwnasptd** [comment]
@i-chvets after taking an extensive look on the `suggestion` images of Katib I see the following pattern:
* All of the images are just a server
* The server doesn't serve any static files, it's just an executable
* They don't require any K8s context

So I would suggest that it would be OK for these ROCKs to just have regular smoke tests, that only verify that the servers can start. WDYT?

**Comment by i-chvets** [comment]
Sound goods good to me, as long as we have a way to verify that server starts for each image, i.e. hit metrics or some other endpoint.
What about these?
katib/cmd/earlystopping/medianstop/v1beta1
katib/cmd/metricscollector/v1beta1/tfevent-metricscollector
katib/cmd/metricscollector/v1beta1/file-metricscollector

**Comment by kimwnasptd** [comment]
For `katib/cmd/earlystopping/medianstop/v1beta1` we can reuse a yaml they already have in https://github.com/kubeflow/katib/blob/master/examples/v1beta1/early-stopping/median-stop.yaml#L19

And for `katib/cmd/metricscollector/v1beta1/file-metricscollector` we can use the yaml they have in https://github.com/kubeflow/katib/blob/master/examples/v1beta1/metrics-collector/file-metrics-collector.yaml

For the last one `katib/cmd/metricscollector/v1beta1/tfevent-metricscollector` upstream is testing with Training Operator. Since this could complicate a lot our CI we can postpone this one for now

**Comment by NohaIhab** [comment]
Based on `katib-config` ConfigMap, the following examples utilize these images:

| Image | upstream example |
| -------- | ------- |
| katib/cmd/earlystopping/medianstop/v1beta1 | [median-stop.yaml](https://github.com/kubeflow/katib/blob/v0.15.0/examples/v1beta1/early-stopping/median-stop.yaml) |
| katib/cmd/metricscollector/v1beta1/tfevent-metricscollector | N/A |
| katib/cmd/metricscollector/v1beta1/file-metricscollector | [file-metrics-collector.yaml](https://github.com/kubeflow/katib/blob/v0.15.0/examples/v1beta1/metrics-collector/file-metrics-collector.yaml) |
| katib/cmd/suggestion/hyperopt/v1beta1 | [random.yaml](https://github.com/kubeflow/katib/blob/v0.15.0/examples/v1beta1/hp-tuning/random.yaml) |
| katib/cmd/suggestion/hyperband/v1beta1 | [hyperband.yaml](https://github.com/kubeflow/katib/blob/v0.15.0/examples/v1beta1/hp-tuning/hyperband.yaml) |
| katib/cmd/suggestion/pbt/v1beta1 | [simple-pbt.yaml](https://github.com/kubeflow/katib/blob/v0.15.0/examples/v1beta1/hp-tuning/simple-pbt.yaml) |
| katib/cmd/suggestion/goptuna/v1beta1 | [cma-es.yaml](https://github.com/kubeflow/katib/blob/v0.15.0/examples/v1beta1/hp-tuning/cma-es.yaml) |
| katib/cmd/suggestion/skopt/v1beta1 | [bayesian-optimization.yaml](https://github.com/kubeflow/katib/blob/v0.15.0/examples/v1beta1/hp-tuning/bayesian-optimization.yaml) | 
| katib/cmd/suggestion/optuna/v1beta1 | [grid.yaml](https://github.com/kubeflow/katib/blob/v0.15.0/examples/v1beta1/hp-tuning/grid.yaml) |
| katib/cmd/suggestion/nas/darts/v1beta1 |  [darts-cpu.yaml](https://github.com/kubeflow/katib/blob/v0.15.0/examples/v1beta1/nas/darts-cpu.yaml) |
| katib/cmd/suggestion/nas/enas/v1beta1 | [enas-cpu.yaml](https://github.com/kubeflow/katib/blob/v0.15.0/examples/v1beta1/nas/enas-cpu.yaml) |

**Comment by i-chvets** [comment]
PR is created https://github.com/canonical/katib-operators/pull/105

**Comment by NohaIhab** [comment]
re-opening to add a test for the `katib/cmd/metricscollector/v1beta1/tfevent-metricscollector` image
