### ISSUE TITLE
Get images script is incorrectly parses some of the images on track/0.15

### ISSUE THREAD

**Issue by i-chvets** [canonical/katib-operators#117]
# Bug Description
List of images produced by `tools/get-images.sh` script produces incorrect image URI. Extra `,` is left for some of them.

# To Reproduce
Execute get images script in repository base directory:
`bash tools/get-images.sh`

# Environment
Charm source code. No additional setting are needed.

# Relevant Log Output
The following is the list images produced by the script. Note extra `,` for some of the images:
```
docker.io/kubeflowkatib/katib-db-manager:v0.15.0
docker.io/kubeflowkatib/katib-controller:v0.15.0
docker.io/kubeflowkatib/katib-ui:v0.15.0
docker.io/kubeflowkatib/suggestion-darts:v0.15.0
docker.io/kubeflowkatib/suggestion-enas:v0.15.0, # <<<<<< extra comma
docker.io/kubeflowkatib/suggestion-goptuna:v0.15.0
docker.io/kubeflowkatib/suggestion-hyperband:v0.15.0
docker.io/kubeflowkatib/suggestion-hyperopt:v0.15.0
docker.io/kubeflowkatib/suggestion-optuna:v0.15.0
docker.io/kubeflowkatib/suggestion-pbt:v0.15.0, # <<<<<< extra comma
docker.io/kubeflowkatib/suggestion-skopt:v0.15.0
docker.io/kubeflowkatib/suggestion-darts:v0.15.0
docker.io/kubeflowkatib/suggestion-enas:v0.15.0, # <<<<<< extra comma
docker.io/kubeflowkatib/suggestion-goptuna:v0.15.0
docker.io/kubeflowkatib/suggestion-hyperband:v0.15.0
docker.io/kubeflowkatib/suggestion-hyperopt:v0.15.0
docker.io/kubeflowkatib/suggestion-optuna:v0.15.0
docker.io/kubeflowkatib/suggestion-pbt:v0.15.0, # <<<<<< extra comma
docker.io/kubeflowkatib/suggestion-skopt:v0.15.0
```
# Additional Context
N/A

**Comment by kimwnasptd** [comment]
Tried the changes locally and they work as expected. Although the more I see these scripts the more I'm convinced they should be written as Python scripts, to make then more readable and maintainable. But this can be a small push from the next week to organize.

Regarding this PR, can we:
1. Make the `tools/get-images.sh` script executable `+x` 
2. Add a shebang at the beginning of the script

Let's be able to do `./tools/get-images.sh`

**Comment by i-chvets** [comment]
Fix has been merged. Closing.
