### ISSUE TITLE
katib-controller: Move large integration test JSON data to separate files

### ISSUE THREAD

**Issue by orfeas-k** [canonical/katib-operators#124]
We should move [large JSON data](https://github.com/canonical/katib-operators/blob/f862faa9436b23c67885a6b3be856f2275fedb29/charms/katib-controller/tests/integration/test_charm.py#L13-L32) used for integration tests outside the [test_charm.py](https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/tests/integration/test_charm.py) file.

**Comment by i-chvets** [comment]
Fix is merged. Closing.
