### ISSUE TITLE
Image references from templates should not be reported by get images script

### ISSUE THREAD

**Issue by i-chvets** [canonical/katib-operators#132]
# Description
Currently, in `katib-controller` there are images that are used as default images for templates. They are define in config as follows:
- `"enas_cpu_template": "docker.io/kubeflowkatib/enas-cnn-cifar10-cpu:v0.16.0-rc.1"`
- `"pytorch_job_template__master": "docker.io/kubeflowkatib/pytorch-mnist-cpu:v0.16.0-rc.1"`
- `"pytorch_job_template__worker": "docker.io/kubeflowkatib/pytorch-mnist-cpu:v0.16.0-rc.1"`

These image references serve as example default images in trial templates. In deployment those will be replaced with other images.
Related [charm code](https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/src/charm.py#L326)

# Solution

~~Option 1. Remove the handling of these images from the charm and render trial templates as is, without replacing templated values.~~
~~Option 2. Not sure if it is feasiable. Do not deploy trial temaplates in the charm.~~

Proposed solution is to remove not needed templates and leave only single Job template which will have Ubuntu default image and sample command.

The following default images should be removed from [`config.yaml`](https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/config.yaml):
- enas_cpu_template:
- pytorch_job_template__master
- pytorch_job_template__worker

Their processing in charm should also be removed: 
https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/src/charm.py#L316
https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/src/charm.py#L316

The following template files should be removed:
https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/src/templates/enasCPUTemplate.yaml.j2
https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/src/templates/pytorchJobTemplate.yaml.j2

The following template file should be updated to include Ubuntu image as default and with sample command that illustrates how to pass parameters.
https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/src/templates/pytorchJobTemplate.yaml.j2

**Comment by kimwnasptd** [comment]
@i-chvets what would you propose?

**Comment by i-chvets** [comment]
> The TrialTemplates are also used by the web apps and can provide a great UX for users to have some defaluts setup. Although an interesting feature would be to allow users to further modify those templates, and provide their own

I liked this suggestion. But it is a feature request.

If we are keeping templated images in we need to provide ROCKs for them to make them more secure.

**Comment by i-chvets** [comment]
Proposed solution is to remove not needed templates and leave only single Job template which will have Ubuntu default image and sample command.

The following default images should be removed from [`config.yaml`](https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/config.yaml):
- enas_cpu_template:
- pytorch_job_template__master
- pytorch_job_template__worker

Their processing in charm should also be removed: 
https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/src/charm.py#L316
https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/src/charm.py#L316

The following template files should be removed:
https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/src/templates/enasCPUTemplate.yaml.j2
https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/src/templates/pytorchJobTemplate.yaml.j2

The following template file should be updated to include Ubuntu image as default and with sample command that illustrates how to pass parameters.
https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/src/templates/pytorchJobTemplate.yaml.j2

**Comment by NohaIhab** [comment]
closed by #146
